#!/bin/bash
#
# Copyright (c) 2021-2026 Logic Magicians Software
#
# This produces the GSA sample files that are referenced in the GSA
# documentation.
#
set -o errexit;
set -o pipefail;
set -o nounset;
source ${SKL_DIR}/scripts/functions

O3_DIR="${SKL_DIR}/system/compiler/o3";

declare -a OPTIONS;
OPTIONS=(                                       \
    "--opt-no-copy-prop"                        \
    "--opt-no-vn"                               \
    "--opt-no-const-prop"                       \
    "--opt-no-dce"                              \
    "--opt-no-ss"                               \
);

declare -a FILES;

# 2026.09.20(thutt): Gimport.Mod requires that the Oberon system
# already be compiled with o3c.  If that has not been done, 'Files'
# module will not be found.
#
FILES=(                                                         \
    "${O3_DIR}/gsa-examples/arithmetic/Aabs.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Aadd.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Aconvert.Mod"            \
    "${O3_DIR}/gsa-examples/arithmetic/Adiv.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Amod.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Amul.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Aneg.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Anot.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Aodd.Mod"                \
    "${O3_DIR}/gsa-examples/arithmetic/Asub.Mod"                \
    "${O3_DIR}/gsa-examples/conditional/Ceql.Mod"               \
    "${O3_DIR}/gsa-examples/conditional/Cgeq.Mod"               \
    "${O3_DIR}/gsa-examples/conditional/Cgtr.Mod"               \
    "${O3_DIR}/gsa-examples/conditional/Cleq.Mod"               \
    "${O3_DIR}/gsa-examples/conditional/Clss.Mod"               \
    "${O3_DIR}/gsa-examples/conditional/Cneq.Mod"               \
    "${O3_DIR}/gsa-examples/guard/Gcase.Mod"                    \
    "${O3_DIR}/gsa-examples/guard/Gfalse.Mod"                   \
    "${O3_DIR}/gsa-examples/guard/Gtrue.Mod"                    \
    "${O3_DIR}/gsa-examples/hardware/Hget.Mod"                  \
    "${O3_DIR}/gsa-examples/hardware/Hgetreg.Mod"               \
    "${O3_DIR}/gsa-examples/hardware/Hmemr.Mod"                 \
    "${O3_DIR}/gsa-examples/hardware/Hmemw.Mod"                 \
    "${O3_DIR}/gsa-examples/hardware/Hput.Mod"                  \
    "${O3_DIR}/gsa-examples/hardware/Hputreg.Mod"               \
    "${O3_DIR}/gsa-examples/logical/Aasl.Mod"                   \
    "${O3_DIR}/gsa-examples/logical/Aasr.Mod"                   \
    "${O3_DIR}/gsa-examples/logical/Alsl.Mod"                   \
    "${O3_DIR}/gsa-examples/logical/Alsr.Mod"                   \
    "${O3_DIR}/gsa-examples/logical/Arol.Mod"                   \
    "${O3_DIR}/gsa-examples/logical/Aror.Mod"                   \
    "${O3_DIR}/gsa-examples/memory-access/Melement.Mod"         \
    "${O3_DIR}/gsa-examples/memory-access/Mfield.Mod"           \
    "${O3_DIR}/gsa-examples/memory-access/Mheap.Mod"            \
    "${O3_DIR}/gsa-examples/memory-access/Mnonlocal.Mod"        \
    "${O3_DIR}/gsa-examples/memory-access/Mvarparm.Mod"         \
    "${O3_DIR}/gsa-examples/memory-operations/Madr.Mod"         \
    "${O3_DIR}/gsa-examples/memory-operations/Marraycopy.Mod"   \
    "${O3_DIR}/gsa-examples/memory-operations/Mdynarrlen.Mod"   \
    "${O3_DIR}/gsa-examples/memory-operations/Mheaptag.Mod"     \
    "${O3_DIR}/gsa-examples/memory-operations/Mcreatenlm.Mod"   \
    "${O3_DIR}/gsa-examples/memory-operations/Mdeletenlm.Mod"   \
    "${O3_DIR}/gsa-examples/memory-operations/Mnewarray.Mod"    \
    "${O3_DIR}/gsa-examples/memory-operations/Mnewdynarray.Mod" \
    "${O3_DIR}/gsa-examples/memory-operations/Mnewrecord.Mod"   \
    "${O3_DIR}/gsa-examples/memory-operations/Mrecordcopy.Mod"  \
    "${O3_DIR}/gsa-examples/memory-operations/Mstringcopy.Mod"  \
    "${O3_DIR}/gsa-examples/memory-operations/Mtbpadr.Mod"      \
    "${O3_DIR}/gsa-examples/memory-operations/Minitialize.Mod"  \
    "${O3_DIR}/gsa-examples/miscellaneous/Gcall.Mod"            \
    "${O3_DIR}/gsa-examples/miscellaneous/Gcap.Mod"             \
    "${O3_DIR}/gsa-examples/miscellaneous/Gcopy.Mod"            \
    "${O3_DIR}/gsa-examples/miscellaneous/Ggate.Mod"            \
    "${O3_DIR}/gsa-examples/miscellaneous/Gimport.Mod"          \
    "${O3_DIR}/gsa-examples/pseudo/Pmayalias.Mod"               \
    "${O3_DIR}/gsa-examples/region/Mcasereg.Mod"                \
    "${O3_DIR}/gsa-examples/region/Menter.Mod"                  \
    "${O3_DIR}/gsa-examples/region/Mexit.Mod"                   \
    "${O3_DIR}/gsa-examples/region/Mgreg.Mod"                   \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sconvert.Mod"        \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sdiff.Mod"           \
    "${O3_DIR}/gsa-examples/set-arithmetic/Selement.Mod"        \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sexcl.Mod"           \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sincl.Mod"           \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sintersection.Mod"   \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sneg.Mod"            \
    "${O3_DIR}/gsa-examples/set-arithmetic/Srange.Mod"          \
    "${O3_DIR}/gsa-examples/set-arithmetic/Ssub.Mod"            \
    "${O3_DIR}/gsa-examples/set-arithmetic/Sunion.Mod"          \
    "${O3_DIR}/gsa-examples/system/Gbit.Mod"                    \
    "${O3_DIR}/gsa-examples/system/Gcondcode.Mod"               \
    "${O3_DIR}/gsa-examples/system/Gfinalize.Mod"               \
    "${O3_DIR}/gsa-examples/system/Gmove.Mod"                   \
    "${O3_DIR}/gsa-examples/system/Gnewblock.Mod"               \
    "${O3_DIR}/gsa-examples/system/Gresetbit.Mod"               \
    "${O3_DIR}/gsa-examples/system/Gsetbit.Mod"                 \
    "${O3_DIR}/gsa-examples/trap/Tassert.Mod"                   \
    "${O3_DIR}/gsa-examples/trap/Tcase.Mod"                     \
    "${O3_DIR}/gsa-examples/trap/Teguard.Mod"                   \
    "${O3_DIR}/gsa-examples/trap/Thalt.Mod"                     \
    "${O3_DIR}/gsa-examples/trap/Tiguard.Mod"                   \
    "${O3_DIR}/gsa-examples/trap/Tindex.Mod"                    \
    "${O3_DIR}/gsa-examples/trap/Treturn.Mod"                   \
    "${O3_DIR}/gsa-examples/trap/Twith.Mod"                     \
    "${O3_DIR}/gsa-examples/type-descriptor/Ginitarr.Mod"       \
    "${O3_DIR}/gsa-examples/type-descriptor/Ginitdarr.Mod"      \
    "${O3_DIR}/gsa-examples/type-descriptor/Ginitrec.Mod"       \
    "${O3_DIR}/gsa-examples/code/straight.Mod"                  \
    "${O3_DIR}/gsa-examples/code/if.Mod"                        \
    "${O3_DIR}/gsa-examples/code/looping.Mod"                   \
);

function main ()
{
    for p in ${FILES[@]}; do
        o3c ${OPTIONS[@]} ${p};
    done;
}

main "${@:-}";
