#!/bin/bash
# Copyright (c) 2026 Logic Magicians Software
#
# Do not run.  Use 'source' to load into environment.
#
if [ -n "${BASH_SOURCE:-}" ]; then
    SCRIPT_PATH="${BASH_SOURCE[0]}"
    SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
elif [ -n "${ZSH_VERSION:-}" ]; then
    SCRIPT_PATH="${(%):-%x}"
    SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
else
    echo "Unrecognized shell.  Not Bash (Linux), nor Zsh (MacOS)." >&2
    SCRIPT_DIR=""
fi

if [ ! -z "${SCRIPT_DIR}" ] ; then
    case "$(uname -s)" in
        Darwin)
            source "${SCRIPT_DIR}/setup.macos" "${@}";
        ;;

        Linux)
            source "${SCRIPT_DIR}/setup.linux" "${@}";
        ;;
    esac
fi;
