#!/bin/bash
#
# Copyright (c) 2021, 2022 Logic Magicians Software
#
# Compile OS using x86-based SKL-targeting compiler.
#
# This produces the basic Oberon OS and compiler testing modules for
# SKL.
set -o errexit;
set -o pipefail;
set -o nounset;
source ${SKL_DIR}/scripts/files.def
source ${SKL_DIR}/scripts/functions

function main ()
{
    echo -e "\n\n*** Building SKL-based Oberon OS & compiler tests.";
    cd ${SKL_DIR}/system;
    skl-skl-oc -n                                   \
        ${OS[*]}                                    \
        ${SKL[*]}                                   \
        ${!COMPILER_TESTS[@]};
}

main "${@}";
