#!/bin/bash
#
# Copyright (c) 2022 Logic Magicians Software
#
#  This script is a wrapper to invoke Python scripts so that the
#  Python interpreter will not modify the source tree.
#
#  It also ensures that all Python scripts get the same runtime
#  environment.
#
set -o errexit;
set -o nounset;
set -o pipefail;

SCRIPT="${0}";
PN=${SCRIPT##*/};      # Program name (remove all before last '/').
DN=${SCRIPT%/*};       # Directory name (removall all after last '/').

function main ()
{
    local opts="-t";
    export PYTHONDONTWRITEBYTECODE=1;

    if [ -v SKL_DIR ] ; then
        python3 ${opts}                                 \
               ${DN}/${PN}.py                           \
               --skl-build-path "$(skl-build-path)"     \
               "${@}";
    else
        echo "SKL environment is not set up.";
        false;
    fi;        
}

main "${@}";
