#!/bin/bash
#
# Copyright (c) 2023 Logic Magicians Software
#
# This script is used to examine code generation differences in the
# SKL compiler by facilitating comparison of the 'before' and 'after'
# disassembly of each compiler module.  It does this by:
#
#   o Checking out all the compiler object files.
#
#   o Disassembling the object files to 'before' files in /tmp.
#
#   o Compiling the compiler.
#
#     This creates the compiler with a new code generator.
#
#   o Compiling the compiler a second time.
#
#     This creates a new compiler with the code generation
#     changes.
#
#   o Disassemble the object files to 'after' files in /tmp.
#
#   o Use md5sum to determine the differences in the 'before' and
#     'after' object files files.
#
#   Following this, a diff program, like 'ediff' in emacs, or 'tkdiff'
#   from the command line can be used to vet the code generation
#   differences.  When all the differences are acceptable, the
#   compiler can be committed.
#
set -o errexit;
set -o pipefail;
set -o nounset;
source ${SKL_DIR}/scripts/functions
source ${SKL_DIR}/scripts/files.def

function output_directory ()
{
    local name="${1}";
    echo "/tmp/codegen/${1}";
}

function disassemble ()
{
    local suffix="${1}";
    local destdir="$(output_directory "${suffix}")";

    mkdir --parents "${destdir}";
    for f in ${SKL[*]/.Mod/.Obj}; do
        disasm --show-dashes ${f} >"${destdir}/$(basename ${f})";
    done;
}


function compare ()
{
    local before="${1}";
    local after="${2}";

    # Sort on the second column (IFS=' ')
    (
        for stage in "${before}" "${after}"; do
            local destdir="$(output_directory "${stage}")";
            for fname in ${SKL[*]/.Mod/.Obj}; do
                local pathname="${destdir}/$(basename ${fname})"
                md5sum ${pathname};
            done;
        done
    )|sort --key=2|sed -e "s./${before}..g" |sed -e "s./${after}..g"|sort|uniq -u;
}


function main ()
{
    git checkout ${SKL[*]/.Mod/.Obj};
    disassemble "before";

    ${SKL_DIR}/scripts/skl-compile-skl;
    disassemble "middle";

    compare "before" "middle"|tee "/tmp/codegen/skl-diffs.1st";

    ${SKL_DIR}/scripts/skl-compile-skl;
    disassemble "after";

    compare "before" "after"|tee "/tmp/codegen/skl-diffs.2nd";
}

main "${@}";
