#!/bin/bash
# Copyright (c) 2021-2026 Logic Magicians Software
#
# Compile and test Oberon modules.
#
set -o errexit;
set -o pipefail;
set -o nounset;


function main()
{
    # Without the following two Python environment variables, Python3
    #   out-of-the-box on Arm-based MacOS fails with:
    #
    #  Fatal Python error: config_get_locale_encoding:  \
    #    failed to get the locale encoding: nl_langinfo(CODESET) failed
    #  Python runtime state: preinitialized
    #
    export PYTHONUTF8=1;
    export PYTHONCOERCECLOCALE=0;

    cd ${SKL_DIR};
    ${SKL_DIR}/scripts/skl-module-test-harness.py --compiler
}
main "${@:-}";
