#!/bin/bash
#
# Copyright (c) 2022-2026 Logic Magicians Software
#
# This produces the Oberon-2 GSA-based compiler for SKL.
#
set -o errexit;
set -o pipefail;
set -o nounset;
source ${SKL_DIR}/scripts/files.def
source ${SKL_DIR}/scripts/functions

function main ()
{
    echo -e "\n\n*** Building SKL-based Oberon-2 GSA compiler.";
    cd ${SKL_DIR}/system;
    skl-skl-oc -n                                   \
        ${O3[*]};
}

main "${@:-}";
